apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: default
  labels:
    # 增加该标签以启用认证信息校验
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: "myjfs"
  metaurl: "redis://:123456@192.168.100.11:6379/0"
  storage: "minio"
  bucket: "http://192.168.100.11:9000/juicefs"
  access-key: "root"
  secret-key: "12345678"
